-- Update business_assessments table to include all form fields
ALTER TABLE business_assessments
  -- Add new array/JSON fields for the challenge sections
  ADD COLUMN IF NOT EXISTS reporting_tools JSONB,
  ADD COLUMN IF NOT EXISTS communication_channels JSONB,
  ADD COLUMN IF NOT EXISTS communication_frequency TEXT,
  ADD COLUMN IF NOT EXISTS communication_pain_points JSONB,
  ADD COLUMN IF NOT EXISTS workflow_bottlenecks JSONB,
  ADD COLUMN IF NOT EXISTS workflow_automation_areas JSONB,
  ADD COLUMN IF NOT EXISTS workflow_collaboration_tools JSONB,
  ADD COLUMN IF NOT EXISTS hr_team_size TEXT,
  ADD COLUMN IF NOT EXISTS hr_pain_points JSONB,
  ADD COLUMN IF NOT EXISTS hr_hiring_volume TEXT,
  
  -- Add columns for existing arrays that need to be stored as JSONB
  ADD COLUMN IF NOT EXISTS goals JSONB,
  ADD COLUMN IF NOT EXISTS compliance_concerns JSONB,
  ADD COLUMN IF NOT EXISTS sales_channels JSONB,
  ADD COLUMN IF NOT EXISTS departments_involved JSONB,
  ADD COLUMN IF NOT EXISTS financial_pain_points JSONB,
  ADD COLUMN IF NOT EXISTS crm_pain_points JSONB,
  ADD COLUMN IF NOT EXISTS onboarding_pain_points JSONB,
  ADD COLUMN IF NOT EXISTS pipeline_lead_source JSONB,
  ADD COLUMN IF NOT EXISTS project_pain_points JSONB,
  ADD COLUMN IF NOT EXISTS software JSONB,
  ADD COLUMN IF NOT EXISTS priorities JSONB,
  
  -- Add the rest of the text/number fields for all sections
  ADD COLUMN IF NOT EXISTS full_name TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS company TEXT,
  ADD COLUMN IF NOT EXISTS role TEXT,
  ADD COLUMN IF NOT EXISTS industry TEXT,
  ADD COLUMN IF NOT EXISTS employees TEXT,
  ADD COLUMN IF NOT EXISTS patient_data TEXT,
  ADD COLUMN IF NOT EXISTS inventory_management TEXT,
  ADD COLUMN IF NOT EXISTS customer_loyalty TEXT,
  ADD COLUMN IF NOT EXISTS owner_involvement TEXT,
  ADD COLUMN IF NOT EXISTS growth_challenges TEXT,
  ADD COLUMN IF NOT EXISTS integration_complexity TEXT,
  ADD COLUMN IF NOT EXISTS decision_makers TEXT,
  ADD COLUMN IF NOT EXISTS invoice_volume TEXT,
  ADD COLUMN IF NOT EXISTS proposal_volume TEXT,
  ADD COLUMN IF NOT EXISTS proposal_approval TEXT,
  ADD COLUMN IF NOT EXISTS proposal_time TEXT,
  ADD COLUMN IF NOT EXISTS onboarding_client_volume TEXT,
  ADD COLUMN IF NOT EXISTS onboarding_duration TEXT,
  ADD COLUMN IF NOT EXISTS pipeline_conversion_rate TEXT,
  ADD COLUMN IF NOT EXISTS pipeline_tracking_method TEXT,
  ADD COLUMN IF NOT EXISTS project_management_method TEXT,
  ADD COLUMN IF NOT EXISTS project_team_size TEXT,
  ADD COLUMN IF NOT EXISTS other_software TEXT,
  ADD COLUMN IF NOT EXISTS automation_level TEXT,
  ADD COLUMN IF NOT EXISTS integration_challenges TEXT,
  ADD COLUMN IF NOT EXISTS specific_pain TEXT,
  ADD COLUMN IF NOT EXISTS success_criteria TEXT,
  ADD COLUMN IF NOT EXISTS previous_automation TEXT,
  ADD COLUMN IF NOT EXISTS previous_experience TEXT,
  ADD COLUMN IF NOT EXISTS decision_timeline TEXT,
  ADD COLUMN IF NOT EXISTS additional_info TEXT,
  ADD COLUMN IF NOT EXISTS consent BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS consultation_requested BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT now(); 