services:
  - type: web
    name: impacto-site
    env: node
    buildCommand: npm install --legacy-peer-deps @react-pdf/renderer && export SKIP_ESLINT=true && export NODE_ENV=production && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISABLE_ESLINT_PLUGIN
        value: true
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
      - key: SKIP_ESLINT
        value: true 