@echo off
echo Stopping any running Next.js processes...
taskkill /f /im node.exe 2>nul

echo Cleaning Next.js cache...
rmdir /s /q .next 2>nul

echo Clearing npm cache...
npm cache clean --force

echo Starting Next.js dev server with clean cache...
npm run dev 